### ISSUE TITLE
Recipes overview

### ISSUE THREAD

**Issue by brdddngs** [brdddngs/capstone-project#2]
### Recipes overview
As a user I want to see some recipes so that I can get some inspiration. 
### Description
Test data should been shown in app like wireframe in capstone book.
### Acceptance criteria
- [ ] all recipes titles should been shown in a list view
- [ ] with tap on title the ingredients and steps should been shown/hide
### Tasks
- [ ] create recipes component
- [ ] add show/hide logic 
### Size
small
