### ISSUE TITLE
App Layout

### ISSUE THREAD

**Issue by brdddngs** [brdddngs/capstone-project#4]
## Add Styling like attached UI design
As a user I want to see the recipes overview in a pretty UI so that my user experience is good.
## Description
Design still needs to be attached
## Acceptance criteria
- [ ] recipes overview looks like design
## Tasks
- [ ] update json data
- [ ] create necessary components
- [ ] add to storybooks
- [ ] testing on mobile device
## Size
large
