### ISSUE TITLE
Overview | Add categories

### ISSUE THREAD

**Issue by brdddngs** [brdddngs/capstone-project#7]
As a user I want to filter my recipes by categories so that I don't have to searching a long time for finding my recipe.
## Description
https://brittakloth233378.invisionapp.com/console/Capstone---Cookbook-ck3fp5d5z0gbt01bggrccsikl/ck3fp5dkb0ih001bgwsc81gno/inspect#project_console
## Acceptance criteria
- [ ] categories are shown like design
## Tasks
- [ ] update recipes.json if necessary 
- [ ] add components
- [ ] add styling
- [ ] add filter logic
- [ ] add to storybooks
- [ ] testing on mobile device
medium
